### ISSUE TITLE
Help is needed for using the ocrb_plus.traineddata

### ISSUE THREAD

**Issue by fime-arsen** [Shreeshrii/tessdata_ocrb#1]
Probably this should not be there. I don't find more appropriate way to ask my question.

I am assuming that this new ocrb_plus.traineddata is something better than one I found here: https://github.com/Exteris/tesseract-mrz/blob/master/lang/OCRB.traineddata.gz?raw=true

1. Is that true? 
2. does the ocrb_plus.traineddata for tesseract 4.0.0 version? 
3. Just downloading the ocr_plus.traineddata and running tesseract 4.0.0 by passing `-l ocrb_plus` and getting the following error:
(1, "read_params_file: Can't open txt Failed loading language 'ocrb_plus' Tesseract couldn't load any languages! Could not initialize tesseract.")
How can I resolve this?

I would really appreciate any suggestion/hint what to use for high accurate MRZ recognition? May be there are some image processing parameters along with optimized train model of the language.

Thanks in advance!

**Comment by Shreeshrii** [comment]
>Just downloading the ocr_plus.traineddata and running tesseract 4.0.0 by passing -l ocrb_plus and getting the following error:

Where did you place the traineddata file? It needs to be in your TESSDATA_PREFIX path ...

**Comment by Shreeshrii** [comment]
> copy the .traineddata file into a 'tessdata' directory. The exact directory will depend both on the type of training data, and your Linux distribtion. Possibilities are /usr/share/tesseract-ocr/tessdata or /usr/share/tessdata or /usr/share/tesseract-ocr/4.00/tessdata.

**Comment by fime-arsen** [comment]
> > Just downloading the ocr_plus.traineddata and running tesseract 4.0.0 by passing -l ocrb_plus and getting the following error:
> 
> Where did you place the traineddata file? It needs to be in your TESSDATA_PREFIX path .

Yes it is under 'tessdata' directory which is already specified to TESSDATA_PREFIX path.

**Comment by Shreeshrii** [comment]
See https://stackoverflow.com/questions/38380965/error-performing-ocr-with-tesseract-read-params-file-cant-open-deu

You need to use  -l and not -1. Ie. Letter l in lower case not number 1

**Comment by Shreeshrii** [comment]
Newer models are now available. See  Readme.md for details.

**Comment by fime-arsen** [comment]
Thank you for the response.
