### ISSUE TITLE
MRZ detection tessdata

### ISSUE THREAD

**Issue by mehullala** [Shreeshrii/tessdata_ocrb#3]
Hello Shree,

can you help me with the latest file for tessdata and if you know accuracy percentage for the same? Appreciate it.

**Comment by Shreeshrii** [comment]
I have uploaded the latest files.

I had included `Arial` as one of the fonts in my trial with 4 fonts which led to lower accuracy in tests so I have removed those.

I have only tested using `lstmeval` with synthetic images. On the small sample  of 16 lines error rate is 0%. On a larger real life sample it will be higher.
