### ISSUE TITLE
How much data did you use for training?

### ISSUE THREAD

**Issue by maky-hnou** [Shreeshrii/tessdata_ocrb#4]
How many images or how much data did you use for training?
I have about 100 documents containing MRZ, is it OK to do the training with 100 MRZ?

**Comment by Shreeshrii** [comment]
I used training text with 255 lines and created the box/tiff using a font.

**Comment by maky-hnou** [comment]
Thank you for your quick answer.

**Comment by Szuuuken** [comment]
Hi,
i don't have any experience with training or fine tuning models, but i have one question ;P
Is the provided training set of 255 lines big enough for a real world scenario or should i increase the training set and rerun the fine tuning on my machine?
