### ISSUE TITLE
Fine tune MRZ dataset on top of your trained model 

### ISSUE THREAD

**Issue by ajinkya933** [Shreeshrii/tessdata_ocrb#5]
Hello @Shreeshrii ,

I have a data set of 144 training images of MRZ, some of these images are repeating. All of these training images are binarized. 

I am using your trained model of 10.8mb from [here](https://github.com/Shreeshrii/tessdata_ocrb) . The results have been good based on your model.

For some images in MRZ using the above model i get following error:

8 instead of B, 
S insted of 5,
O inplace of 0 etc

To avoid this I have retrained the model based on my dataset. To retrain this model I used https://github.com/OCR-D/ocrd-train. But, using this I can only train the entire model from scratch(I cannot specify START_MODEL = parameter in the [Makefile](https://github.com/OCR-D/ocrd-train/blob/master/Makefile))  on my own dataset. And the results are not accurate enough.

I modified the make file as follows I want to use your model as a baseline and train my data set on top of it, so that only the changes that I want to make are made without disturbing your original models output. Source of Makefile : https://github.com/OCR-D/ocrd-train/blob/master/Makefile

```
export

SHELL := /bin/bash
LOCAL := $(PWD)/usr
PATH := $(LOCAL)/bin:$(PATH)
TESSDATA =  $(LOCAL)/share/tessdata

# Name of the model to be built. Default: $(MODEL_NAME)
MODEL_NAME = foo

# Name of the model to continue from. Default: '$(START_MODEL)'
START_MODEL = data/shree/ocrb_one.traineddata

LAST_CHECKPOINT = data/checkpoints/$(MODEL_NAME)_checkpoint

# Name of the proto model. Default: '$(PROTO_MODEL)'
PROTO_MODEL = data/$(MODEL_NAME)/$(MODEL_NAME).traineddata

# No of cores to use for compiling leptonica/tesseract. Default: $(CORES)
CORES = 4

# Leptonica version. Default: $(LEPTONICA_VERSION)
LEPTONICA_VERSION := 1.75.3

# Tesseract commit. Default: $(TESSERACT_VERSION)
TESSERACT_VERSION := fd492062d08a2f55001a639f2015b8524c7e9ad4

# Tesseract model repo to use. Default: $(TESSDATA_REPO)
TESSDATA_REPO = _best

# Ground truth directory. Default: $(GROUND_TRUTH_DIR)
GROUND_TRUTH_DIR := data/ground-truth

# Normalization Mode - see src/training/language_specific.sh for details. Default: $(NORM_MODE)
NORM_MODE = 2

# Page segmentation mode. Default: $(PSM)
PSM = 6

# Ratio of train / eval training data. Default: $(RATIO_TRAIN)
RATIO_TRAIN := 0.90
```
However I get the following error each time I mention 
`START_MODEL = data/shree/ocrb_one.traineddata`

```

python generate_line_box.py -i "data/ground-truth/99_1.tif" -t "data/ground-truth/99_1.gt.txt" > "data/ground-truth/99_1.box"
python generate_line_box.py -i "data/ground-truth/99_2.tif" -t "data/ground-truth/99_2.gt.txt" > "data/ground-truth/99_2.box"
python generate_line_box.py -i "data/ground-truth/9_1.tif" -t "data/ground-truth/9_1.gt.txt" > "data/ground-truth/9_1.box"
python generate_line_box.py -i "data/ground-truth/9_2.tif" -t "data/ground-truth/9_2.gt.txt" > "data/ground-truth/9_2.box"
find data/ground-truth -name '*.box' -exec cat {} \; > "data/all-boxes"
mkdir -p data/data/shree/ocrb_one.traineddata
combine_tessdata -u /home/ajinkya/Desktop/Tesseract4/ocrd-train/usr/share/tessdata/data/shree/ocrb_one.traineddata.traineddata  data/data/shree/ocrb_one.traineddata/data/shree/ocrb_one.traineddata
Failed to read /home/ajinkya/Desktop/Tesseract4/ocrd-train/usr/share/tessdata/data/shree/ocrb_one.traineddata.traineddata
Makefile:98: recipe for target 'data/unicharset' failed
make: *** [data/unicharset] Error 1
```
I rechecked the path ' data/shree/ocrb_one.traineddata' is correct.
Is there something I am missing. Or should I just import your model in place of eng.traineddata in the make file and that should work ?

```
# Download tesseract-langs
tesseract-langs: $(TESSDATA)/eng.traineddata
```

**Comment by Shreeshrii** [comment]
In ocrd-train, the start model needs to be the name of the language/model used as base. So it should not be `START_MODEL = data/shree/ocrb_one.traineddata`. You can place this model in your tessdata directory and then refer it to as ` START_MODEL = ocrb_one`.

Please note that I have not used ocrd-train for training.

**Comment by ajinkya933** [comment]
That produces the same error. Which platform did you use to train the MRZ data? would you mind sharing with me the steps so that I can try to funetune better through your guidelines

**Comment by Shreeshrii** [comment]
I did training on ubuntu. The steps are already given in repo. See https://github.com/Shreeshrii/tessdata_ocrb/blob/master/finetune-ocrb.sh

**Comment by ajinkya933** [comment]
Thank you. I was able to run your code by manually running each function in the shell script https://github.com/Shreeshrii/tessdata_ocrb/blob/master/finetune-ocrb.sh  

What I understood is:

1) Take manual text input by physically typing  ([eng.MRZ.eval.training_text](https://github.com/Shreeshrii/tessdata_ocrb/blob/master/eng.MRZ.training_text)).
2) Convert it into image by using tesstrain.sh
3) make box files for your annotated text.
4) Convert .box+ .tif to lstm 
5) Start training

I want to train tesseract using ocrd-train and tesseract version 4.0 
From my research I came to know that using gray scale images for training increases accuracy for tesseract 4.0. 
Is there any way where in I can convert ([eng.MRZ.eval.training_text](https://github.com/Shreeshrii/tessdata_ocrb/blob/master/eng.MRZ.training_text)) to a gray scale image ?
so that I can use that + my custom gathered passport data to retrain tesseract 4

**Comment by Shreeshrii** [comment]
>make box files for your annotated text.

tesstrain.sh runs text2image program that generates the box/tif pairs.

>Convert .box+ .tif to lstm

lstmf

>Is there any way where in I can convert (eng.MRZ.eval.training_text) to a gray scale image ?

You can use any image manipulation program to convert the text2image created tifs to greyscale.
